### ISSUE TITLE
[Issue]: Versioning mismatch - WHL vs SO

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rocPyDecode#102]
### Problem Description

CMakeList lists the version library here - https://github.com/ROCm/rocPyDecode/blob/5d386354b529efa784057f699db92ef7e092d186/CMakeLists.txt#L26

Current version lists as 0.1.0

WHL sets version 1.0.0 - https://github.com/ROCm/rocPyDecode/blob/5d386354b529efa784057f699db92ef7e092d186/setup.py#L82 which is a mismatch.

@essamROCm - can we set all versions to 0.2.0 in PR #99 ?

### Operating System

Ubuntu

### CPU

ALL

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.0

**Comment by essamROCm** [comment]
@kiritigowda 
Hi Kirit
Sorry I actually made the changes already and push it, but was surprised that the PR99 was already merged, although I wasn't done with it.
I'll have to make a new PR for this version mismatch.

**Comment by essamROCm** [comment]
Fixed in [PR 103]  : https://github.com/ROCm/rocPyDecode/pull/103

**Comment by essamROCm** [comment]
Fixed in [PR 103] : https://github.com/ROCm/rocPyDecode/pull/103
