### ISSUE TITLE
[Feature]: Support for different Python versions with Pybind

### ISSUE THREAD

**Issue by LakshmiKumar23** [ROCm/rocPyDecode#119]
### Suggestion Description

Need to support non-default python versions with respective pybind version
Ex: Ubuntu22.04 - Python3.10 - `apt install pybind11-dev` brings in 2.9.2. 
If, Ubuntu22.04 - Python3.10 - needs pybind 2.12+

**Comment by essamROCm** [comment]
@LakshmiKumar23 
Does that mean we should always bring pybind 2.12, not less version, and make it required version if Py is 3.10 or higher?
Can you please elaborate more?

**Comment by essamROCm** [comment]
Resolved in [PR#122](https://github.com/ROCm/rocPyDecode/pull/122)
